[package]
name = "milo-parser-generator"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
indexmap = "2.0.0"
lazy_static = "1.4.0"
proc-macro2 = "1.0.63"
quote = "1.0.28"
syn = { version  = "2.0.18", features = [ "full" ] }
